void main() {

    var sample = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............""";

    System.out.println(sample);

    // i'll try finding all the beams
    // first beam enters the manifold at (S)
    // beam entering splitter creates 2 new beams (^)
    // beams always flow down
    // beams end at a splitter or when they would leave the manifold

    var g = Grid.gridify(sample);
    System.out.println(g);
}
