# LogManager logLevel creates LogRecords for all log events
.level=ALL

# Add a console logger
handlers=java.util.logging.ConsoleHandler

# ConsoleHandler logLevel publishes info level events and above
java.util.logging.ConsoleHandler.level=INFO

# Helpful stackOverflow:
#   https://stackoverflow.com/questions/6315699/why-are-the-level-fine-logging-messages-not-showing